### ISSUE TITLE
Incorrect blockchain statement. 

### ISSUE THREAD

**Issue by ghost** [luuksommers/computer-lang.org#2]
This must be @berendhaan's fault, but the readme mentions a blockchain. Im 69% sure that we're utilizing a quantum blockchain.

Please correct this grave mistake, as this might give potential architects the wrong impression when claps need to be given.

**Comment by berendhaan** [comment]
Sir you are correct. Will send a PR ASAP.

**Comment by ghost** [comment]
@berendhaan Is this project abandoned?

**Comment by berendhaan** [comment]
Fixed in #4
